### PR TITLE
Aplat 3769 navbar style fix

### PR DESCRIPTION
**Pull request by UshaKundapur**

### CODE REVIEW

**Comment by mtomcal** [comment]
Sadly, this doesn't fix the root of the problem. The navbar will not extend to 100% of the width of the container because it uses floats. The navbar has to have the blue background bar expand beyond the width of the parent Navbar items.

To test this change the storybook container here: https://github.com/Attainia/attainia-web-components/pull/129/files#diff-e87de5daeab5679d2db9a4ead3fa9e48R102

From
```js

**Comment by mtomcal** [comment]
Here is a flexbox tutorial navigation tutorial: https://medium.freecodecamp.org/how-to-create-a-fully-responsive-navbar-with-flexbox-a4435d175dd3

And here is the cheatsheet for flexbox from css tricks:
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by UshaKundapur** [comment]
@mtomcal I know, it's not full width here... But we have to change the parent of the UL element to add background color to full width. I did try changing this width to full width, then the background color extends to the children <ul> Which are dropdowns.  So decided to add background color for `sidebar` in `Attainia web component`

**Comment by UshaKundapur** [comment]
`Here is a flexbox tutorial navigation tutorial: https://medium.freecodecamp.org/how-to-create-a-fully-responsive-navbar-with-flexbox-a4435d175dd3` - This works better for the Horizontal navbar that doesn't have dropdowns :(

**Comment by UshaKundapur** [comment]
@mtomcal Please see the PR `https://github.com/Attainia/attainia-web-components/pull/130` and comments. I have made the changes you have said and checked in Attainia Branded Components and it's not working out. Please tell me If I have missed something you said.

**Pull request merged**
